#!/usr/bin/env bash
# Source:
# https://elixir.hexdocs.pm/Port.html#module-orphan-operating-system-processes
# See also:
# elixirforum.com/t/extra-watcher-doesnt-get-killed-when-shutting-down-phoenix/2807

# Start the program in the background
exec "$@" &
pid1=$!

# Silence warnings from here on
exec >/dev/null 2>&1

# Read from stdin in the background and
# kill running program when stdin closes
exec 0<&0 $(
  while read; do :; done
  kill -KILL $pid1
) &
pid2=$!

# Clean up
wait $pid1
ret=$?
kill -KILL $pid2
exit $ret
